name: Build Simple File Organiser

on:
  push:
  workflow_dispatch:

jobs:    
  build-executable:
    name: Build executable
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: "pip"
        cache-dependency-path: simple-file-organiser/requirements.txt
    - name: Install dependencies
      run: pip install -r simple-file-organiser/requirements.txt
    - name: Build executable
      shell: bash
      run: |
        pyinstaller \
          --onefile \
          --noconsole \
          --name "Simple File Organiser"
          simple-file-organiser/src/main.py
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: simple-file-organiser-${{ matrix.os }}-${{ github.sha }}
        path: dist/Simple\ File\ Organiser
        if-no-files-found: error
